sudo: required
services:
  - docker

before_install:
  - docker build -t visionsofdrifting/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run visionsofdrifting/react-test npm test -- --coverage

after_success:
  - docker build -t visionsofdrifting/multi-client ./client
  - docker build -t visionsofdrifting/multi-nginx ./nginx
  - docker build -t visionsofdrifting/multi-server ./server
  - docker build -t visionsofdrifting/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push visionsofdrifting/multi-client
  - docker push visionsofdrifting/multi-nginx
  - docker push visionsofdrifting/multi-server
  - docker push visionsofdrifting/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-572232958174"
  # Path doesn't exist by default. It is created on first push
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
