sudo: required
services:
  - docker

before_install:
  - docker build -t visionsofdrifting/dockerized-app -f Dockerfile.dev .

script:
  - docker run visionsofdrifting/dockerized-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerized-app"
  env: "DockerizedApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-572232958174"
  # Path doesn't exist by default. It is created on first push
  bucket_path: "dockerized-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
